In [1]:
import numpy as np
import pandas as pd
import main
las_data = pd.read_csv(main.csv_las_out_full_path, delimiter=';')

In [2]:
wells_list = np.unique(las_data['well_name'].values).tolist()
len(wells_list)

223

In [10]:
las_data_cutted = pd.DataFrame()

for well in wells_list:    
    well_las_data = las_data[las_data['well_name'] == well]
    cuted_well_las, not_empty = main.cut_data_frame_by_satur(well_las_data)
    if not_empty:
         las_data_cutted = las_data_cutted.append(cuted_well_las)

las_data_cutted.describe()

,STRT,STOP,DEPT,aps,rp,kp,kgl,kpr,kvo,kng,lit,satur
count,308924.000000,308924.000000,308924.000000,127606.000000,188709.000000,191843.000000,182965.000000,191968.000000,177069.000000,308924.000000,308924.000000,308924.000000
mean,2495.859367,3045.657912,2779.719434,0.391987,15.011739,0.134285,0.241503,28.421996,0.802113,0.040608,0.309309,1.511475
std,787.343964,421.575971,603.898441,0.322511,141.618242,0.065662,0.116804,123.826467,0.272653,0.137920,0.462210,2.823551
min,860.000000,1776.600000,860.000000,0.000000,0.300000,0.002000,0.041000,0.000000,0.204000,0.000000,0.000000,0.000000
25%,2473.400000,2844.400000,2661.900000,0.100000,4.300000,0.092000,0.144000,0.100000,0.494000,0.000000,0.000000,0.000000
50%,2756.400000,3055.400000,2894.800000,0.320000,6.100000,0.125000,0.233000,0.100000,1.000000,0.000000,0.000000,0.000000
75%,2999.400000,3296.200000,3163.700000,0.690000,8.900000,0.161000,0.340000,3.600000,1.000000,0.000000,1.000000,2.000000
max,3466.000000,3936.000000,3901.500000,1.000000,8635.100000,0.368000,0.465000,1759.700000,1.000000,0.796000,1.000000,10.000000